title = "Shriya Bayalkoti"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Shriya Bayalkoti"
  headline = "Hi stranger! I am an IT student persuing a Bachelors degree from [Janamaitri Multiple Campus](https://www.janamaitri.edu.np/). I am a to-be PHP developer. Nice to meet you."
  image = "shriya.jpg"
  links = [
    { link = { href = "/shriyaCV.pdf", text = "Download my CV >>", icon = "" } },
    { github = "https://github.com/shriyana" },
    { email = "mailto:shreeyana05@gmail.com"},
    { link = { href = "styles/", text = "Reach me", target = "_self" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
